name: data-analysis-ges
channels:
  - conda-forge
dependencies:
  - python=3.8
  - jupyterlab=2.2.6
  - pandas=1.1.1
  - matplotlib=3.3.1
  - numpy=1.19.1
  - seaborn=0.10.1
  - bokeh=2.2.0
  - altair=4.1.0
  - plotly=4.9.0
  - pip=20.2.2
  - pip:
    - streamlit